version: 2.1
orbs:
  node: circleci/node@4.1.0
  slack: circleci/slack@4.1.4
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      # - run:
      #     command: yarn run test
      #     name: Run YARN tests
      # - slack/notify:
          # channel: channel_id
          # color: '#42e2f4'
          # mentions: 'foo,bar,'
          # message: This is a custom message notification
          # webhook: '${SLACK_WEBHOOK}'
workflows:
    build-and-test:
      jobs:
        - build-and-test
